title: "Alp Efe Karalar"
email: aek5621@psu.edu
description: >- # this means to ignore newlines until "baseurl:"
  This is a website I created using GitHub Pages and a repository from MLH!
  
baseurl: "/" 
url: "/portfolio-template" 
twitter_username: mlhacks
github_username:  mlh-fellowship

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
